/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package operatorPackage;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Graphics;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
/**
 *
 * @author prasu
 */


public class NewCustomer extends javax.swing.JInternalFrame {
    String global_name;
String global_ip;
String global_phno;
String global_userid;
int global_operator;

    /**
     * Creates new form Customer
     */String url="jdbc:mysql://cloud-db.cv9uvbky3tsl.ap-south-1.rds.amazonaws.com/universal";
            String un="root";
            String pass="Password123";
            Connection con;
    public NewCustomer() {
        initComponents();
        autoId();
        broadband();
        operators();
         jComboBox1.setSelectedIndex(-1);
         jComboBox2.setSelectedIndex(-1);
         jComboBox3.setSelectedIndex(-1);
         jComboBox4.setSelectedIndex(-1);
        Connection con;
    
       
        view();
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
 public void filter()
 {
     Connection con;
        String name="";
       if(jComboBox3.getSelectedIndex() != -1)
       {name=jComboBox3.getSelectedItem().toString();
       }
      String  broadband="";
        if(jComboBox4.getSelectedIndex() != -1)
       {broadband=jComboBox4.getSelectedItem().toString();
       }
       
    
       
        String cust_name=txtCust.getText().toUpperCase();
       
        try {
            jTableClient.setModel(new DefaultTableModel(null,new String[]{"CUST_NAME","CUST_IP","CUST_CONTACT","OPERATOR NAME","BROADBAND"}));
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st1=con.createStatement();
                    Statement st2=con.createStatement();
                    
                  String query1=" select cust_name,cust_user_id,cust_contact_no,"
                          + "operator_name,cust_broadband from customer join operator "
                          + "where cust_operator_id=operator_id ";
                  
                  String query2=" select count(*)from customer join operator where cust_operator_id=operator_id ";
                 
                          
                  
                  if(name.length()!=0)
                  {
                      
                      query1=query1+" AND operator_name='"+name+"'";
                     query2=query2+"AND operator_name='"+name+"'";
                     


                  }
                 
                  if(cust_name.length()!=0)
                  { cust_name="%"+cust_name+"%";
                      
                      query1=query1+" AND cust_name like'"+cust_name+"'";
                      query2=query2+"AND cust_name like'"+cust_name+"'";
                    
                      
                  }
                  
                  if(broadband.length()!=0)
                  { 
                      
                      query1=query1+" AND cust_broadband ='"+broadband+"'";
                      query2=query2+"AND cust_broadband ='"+broadband+"'";
                    
                      
                  }
                  
                  query1=query1+"order by cust_id desc ;";
                  query2=query2+";";
                  
                 // System.out.print(query1);
        
        ResultSet rs1=st1.executeQuery(query1);
         ResultSet rs2=st2.executeQuery(query2);
          
         rs2.next();
         
         
         txtCount.setText(rs2.getString(1));

        DefaultTableModel model=(DefaultTableModel)jTableClient.getModel();
        while(rs1.next())
        {model.addRow(new String[]{rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4),rs1.getString(5)});         
        }
        
        }     
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
           
 }
           
public void view()
{
     try{ 
         
         txtCount.setText("");
            jTableClient.setModel(new DefaultTableModel(null,new String[]{"CUST_NAME","CUST_IP","CUST_CONTACT","OPERATOR NAME","BROADBAND"}));
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st1=con.createStatement();
                  Statement st2=con.createStatement();
                  Statement st3=con.createStatement();
                  String query1=" select cust_name,cust_user_id,cust_contact_no,"
                          + "operator_name,cust_broadband from customer join operator "
                          + "where cust_operator_id=operator_id order by cust_id desc;";
                  
                  String query2=" select count(*)from customer join operator where cust_operator_id=operator_id;";
                 

       ResultSet rs1=st1.executeQuery(query1);
         ResultSet rs2=st2.executeQuery(query2);
          
         
         rs2.next();
         
         
         txtCount.setText(rs2.getString(1));
         txtCust.setText("");
          jComboBox3.setSelectedIndex(-1);
           jComboBox4.setSelectedIndex(-1);

        DefaultTableModel model=(DefaultTableModel)jTableClient.getModel();
        while(rs1.next())
        {model.addRow(new String[]{rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4),rs1.getString(5)});         
        //System.out.println(rs1.getString(2));
        }
        
        }       
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    public void autoId ()
    {
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            
                  Statement st=con.createStatement();
        
        ResultSet rs=st.executeQuery("select max(cust_id) from customer;");
        rs.next();
        rs.getString("Max(cust_id)");
        if(rs.getString("Max(cust_id)")==null)
            
        {
            jLabel11.setText("001");
            jLabel10.setText("001");
        }
        else
        {
           long id=Integer.parseInt(rs.getString("Max(cust_id)"));
           id++;
           jLabel11.setText(String.format("%03d", id));
           jLabel10.setText(String.format("%03d", id));
        }
                  } 
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    public void operators()
    {Connection con;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            Statement st=con.createStatement();
        
        ResultSet rs=st.executeQuery("select operator_name from operator;");
        
         jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        while(rs.next())
        {jComboBox1.addItem(rs.getString(1));
            jComboBox2.addItem(rs.getString(1));
        jComboBox3.addItem(rs.getString(1));
       
        }
        
        
       
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
    }
    
    
     public void broadband()
    { Connection con;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url,un,pass);
            Statement st=con.createStatement();
        
        ResultSet rs=st.executeQuery("select cust_broadband from customer group by cust_broadband;");
        
         jComboBox4.removeAllItems();
        
        while(rs.next())
        {jComboBox4.addItem(rs.getString(1));
            
       
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            
     
     public static boolean isValidIPAddress(String ip)
    {
 
        // Regex for digit from 0 to 255.
        String zeroTo255
            = "(\\d{1,2}|(0|1)\\"
              + "d{2}|2[0-4]\\d|25[0-5])";
 
        // Regex for a digit from 0 to 255 and
        // followed by a dot, repeat 4 times.
        // this is the regex to validate an IP address.
        String regex
            = zeroTo255 + "\\."
              + zeroTo255 + "\\."
              + zeroTo255 + "\\."
              + zeroTo255;
 
        // Compile the ReGex
        Pattern p = Pattern.compile(regex);
 
        // If the IP address is empty
        // return false
        if (ip == null) {
            return false;
        }
 
        // Pattern class contains matcher() method
        // to find matching between given IP address
        // and regular expression.
        Matcher m = p.matcher(ip);
 
        // Return if the IP address
        // matched the ReGex
        return m.matches();
    }
     
     public static boolean isValidPhno(String phno)
     { String regex = "(0/91)?[1-9][0-9]{9}";
     return phno.matches(regex);
         
     }
     
     public static boolean isValidUsername(String name)
    {
  
        // Regex to check valid username.
        String regex = "[a-z]+[0-9]*[_][cC][kK][cC][tT]";
  
        // Compile the ReGex
        Pattern p = Pattern.compile(regex);
  
        // If the username is empty
        // return false
        if (name == null) {
            return false;
        }
  
        // Pattern class contains matcher() method
        // to find matching between given username
        // and regular expression.
        Matcher m = p.matcher(name);
  
        // Return if the username
        // matched the ReGex
        return m.matches();
    }
     
      public static boolean isValidName(String phno)
     { String regex = "[A-Za-z]+[[ ]*[A-Za-z]*]*";
     return phno.matches(regex);
         
     }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPhno1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtIp6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        gtplCustUpdate = new javax.swing.JButton();
        clearGtplForm = new javax.swing.JButton();
        gtplCustAdd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtIp1 = new javax.swing.JTextField();
        txtIp2 = new javax.swing.JTextField();
        txtIp3 = new javax.swing.JTextField();
        txtIp4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel230 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPhno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        AllianceCustAdd = new javax.swing.JButton();
        clearAllianceForm = new javax.swing.JButton();
        AllianceCustupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        txtCust = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        txtCount = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        filter1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));
        setClosable(true);
        setForeground(new java.awt.Color(255, 123, 162));
        setIconifiable(true);
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(75, 72, 103));

        jTabbedPane1.setBackground(new java.awt.Color(204, 170, 102));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 170, 102));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Customer No");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("jLabel10");

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Customer Name");

        txtName1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });
        txtName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtName1KeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Customer Ph No");

        txtPhno1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPhno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhno1KeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("User ID");

        txtIp6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIp6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIp6KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Local Operator");

        jComboBox2.setMinimumSize(new java.awt.Dimension(5, 19));
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        gtplCustUpdate.setBackground(new java.awt.Color(51, 102, 255));
        gtplCustUpdate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gtplCustUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/update Customer.png"))); // NOI18N
        gtplCustUpdate.setText("Update");
        gtplCustUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtplCustUpdateActionPerformed(evt);
            }
        });
        gtplCustUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gtplCustUpdateKeyPressed(evt);
            }
        });

        clearGtplForm.setBackground(new java.awt.Color(204, 170, 102));
        clearGtplForm.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clearGtplForm.setForeground(new java.awt.Color(255, 255, 255));
        clearGtplForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/Clear customer.png"))); // NOI18N
        clearGtplForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearGtplFormActionPerformed(evt);
            }
        });
        clearGtplForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearGtplFormKeyPressed(evt);
            }
        });

        gtplCustAdd.setBackground(new java.awt.Color(51, 153, 0));
        gtplCustAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gtplCustAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/addCustomer.png"))); // NOI18N
        gtplCustAdd.setText("Add");
        gtplCustAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtplCustAddActionPerformed(evt);
            }
        });
        gtplCustAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gtplCustAddKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtPhno1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(gtplCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gtplCustUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearGtplForm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtPhno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gtplCustUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gtplCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clearGtplForm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("GTPL", jPanel4);

        jPanel5.setBackground(new java.awt.Color(141, 181, 128));

        txtIp1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtIp2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtIp3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIp3ActionPerformed(evt);
            }
        });

        txtIp4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIp4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIp4KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Customer No");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("jLabel10");

        jLabel230.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel230.setForeground(new java.awt.Color(0, 0, 102));
        jLabel230.setText("Customer Name");

        txtName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Customer Ph No");

        txtPhno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPhno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhnoKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("IP Address");

        jLabel19.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Local Operator");

        jComboBox1.setMinimumSize(new java.awt.Dimension(5, 19));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        AllianceCustAdd.setBackground(new java.awt.Color(51, 153, 0));
        AllianceCustAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AllianceCustAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/addCustomer.png"))); // NOI18N
        AllianceCustAdd.setText("Add");
        AllianceCustAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllianceCustAddActionPerformed(evt);
            }
        });
        AllianceCustAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AllianceCustAddKeyPressed(evt);
            }
        });

        clearAllianceForm.setBackground(new java.awt.Color(141, 181, 128));
        clearAllianceForm.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clearAllianceForm.setForeground(new java.awt.Color(255, 255, 255));
        clearAllianceForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/Clear customer.png"))); // NOI18N
        clearAllianceForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllianceFormActionPerformed(evt);
            }
        });
        clearAllianceForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearAllianceFormKeyPressed(evt);
            }
        });

        AllianceCustupdate.setBackground(new java.awt.Color(51, 102, 255));
        AllianceCustupdate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AllianceCustupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/update Customer.png"))); // NOI18N
        AllianceCustupdate.setText("Update");
        AllianceCustupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllianceCustupdateActionPerformed(evt);
            }
        });
        AllianceCustupdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AllianceCustupdateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel230, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(txtIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel19)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(AllianceCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AllianceCustupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllianceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10)
                        .addComponent(jLabel18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel230)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AllianceCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AllianceCustupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clearAllianceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("ALLIANCE", jPanel5);

        jTableClient.setBackground(new java.awt.Color(38, 110, 115));
        jTableClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableClient.setForeground(new java.awt.Color(255, 255, 255));
        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUST NAME", "CUST IP", "CUST CONTACT", "OPERATOR NAME", "BROADBAND"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClient.setColumnSelectionAllowed(true);
        jTableClient.setFocusable(false);
        jTableClient.setGridColor(new java.awt.Color(0, 0, 0));
        jTableClient.setRowSelectionAllowed(false);
        jTableClient.setSelectionBackground(new java.awt.Color(38, 70, 63));
        jTableClient.setShowGrid(true);
        jTableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClient);

        txtCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustKeyPressed(evt);
            }
        });

        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox3KeyPressed(evt);
            }
        });

        txtCount.setBackground(new java.awt.Color(255, 255, 0));
        txtCount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCount.setForeground(new java.awt.Color(0, 0, 0));
        txtCount.setText("jTextField1");
        txtCount.setFocusable(false);
        txtCount.setRequestFocusEnabled(false);
        txtCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 0, 204));
        reset.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/ReloadFilter.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        reset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resetKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer");

        jComboBox4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox4KeyPressed(evt);
            }
        });

        filter1.setBackground(new java.awt.Color(255, 0, 51));
        filter1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        filter1.setForeground(new java.awt.Color(255, 255, 255));
        filter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/Filter.png"))); // NOI18N
        filter1.setText("Filter");
        filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter1ActionPerformed(evt);
            }
        });
        filter1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filter1KeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Operator ");

        jLabel15.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Broadband");

        jLabel16.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("No. of Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(1, 1, 1)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCust, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)
                                .addComponent(jLabel15)
                                .addGap(2, 2, 2)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 539, Short.MAX_VALUE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
      
        view();
    }//GEN-LAST:event_resetActionPerformed

    private void resetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resetKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetKeyPressed

    private void txtCustKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustKeyPressed
        // TODO add your handling code here:

       
        filter();
    }//GEN-LAST:event_txtCustKeyPressed

    private void jComboBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyPressed
        // TODO add your handling code here:
        

        filter();
    }//GEN-LAST:event_jComboBox3KeyPressed

    private void txtCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountActionPerformed

    private void jComboBox4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4KeyPressed

    private void filter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter1ActionPerformed
        // TODO add your handling code here:
        filter();
    }//GEN-LAST:event_filter1ActionPerformed

    private void filter1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filter1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter1KeyPressed

    private void txtIp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIp3ActionPerformed

    private void gtplCustAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gtplCustAddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtplCustAddKeyPressed

    public void insertgtpl()
    { try {
            // TODO add your handling code here:
            int cust_id=Integer.parseInt(jLabel11.getText());
            String cust_Name=txtName1.getText().toUpperCase();
//System.out.print(cust_Name);
            int existingEntry;
            String cust_ip=txtIp6.getText();
            String cust_phno=txtPhno1.getText();
            //System.out.print(cust_ip);
            boolean flag1=isValidUsername(cust_ip);
            boolean flag2=isValidPhno(cust_phno);
            boolean flag3=isValidName(cust_Name);
            
            if((flag1 && flag2&& flag3)==false)
            {
                
               if(flag1==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid UserName</b></html>");
               else if(flag2==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Phone No</b></html>");
               else if(flag3==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Name</b></html>");
  
            }
           else
               

            {

                String operator=null;

                //System.out.print(jComboBox1.getSelectedItem().toString());
                if(jComboBox2.getSelectedIndex() != -1)
                {operator=jComboBox2.getSelectedItem().toString();
                    int operator_id=1;
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection(url,un,pass);

                    Statement st=con.createStatement();

                    Statement st2=con.createStatement();
                    Statement st3=con.createStatement();
                    

                    ResultSet rs=st2.executeQuery("SELECT operator_id FROM universal.operator where operator_name='"+operator+"';");
                    rs.next();
                    ResultSet rs2=st3.executeQuery("SELECT EXISTS(SELECT * from customer WHERE cust_user_id='"+cust_ip+"');");
                    rs2.next();

                    existingEntry=Integer.parseInt(rs2.getString(1));

                    if(existingEntry==0)
                    {
                        operator_id=Integer.parseInt(rs.getString(1));
                        String query5="insert into customer(cust_id,cust_Name,cust_user_id,cust_operator_id,cust_contact_no,cust_broadband) values('"+cust_id+"','"+cust_Name+"','"+cust_ip+"','"+operator_id+"','"+cust_phno+"','GTPL');";

                        int i=st.executeUpdate(query5);

                        JOptionPane.showMessageDialog(this,"<html><b style=\"color:green;font-size:20px;\">Record updated</b></html>");
                        view();
                        autoId ();
                        txtName1.setText("");

                        txtIp6.setText("");
                        txtPhno1.setText("");

                        jComboBox2.setSelectedIndex(-1);

                    }   else
                    JOptionPane.showMessageDialog(this,"<html><b style=\"color:yellow;font-size:20px;\">User Id Already Exists</b></html>");

                }  else
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Local Operator Not Selected</b></html>");

            }
            
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void gtplCustAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtplCustAddActionPerformed
        // TODO add your handling code here:
        insertgtpl();
       
    }//GEN-LAST:event_gtplCustAddActionPerformed
    public void insertAlliance()
    {
          try {
            // TODO add your handling code here:
            int cust_id=Integer.parseInt(jLabel10.getText());
            String cust_Name=txtName.getText().toUpperCase();

            String cust_ip1=txtIp1.getText();
            String cust_ip2=txtIp2.getText();
            String cust_ip3=txtIp3.getText();

            String cust_ip4=txtIp4.getText();
            int existingEntry;
            String cust_ip=cust_ip1+"."+cust_ip2+"."+cust_ip3+"."+cust_ip4;
            String cust_phno=txtPhno.getText();
            //System.out.print(cust_ip);
            boolean flag1=isValidIPAddress(cust_ip);
            boolean flag2=isValidPhno(cust_phno);
            boolean flag3=isValidName(cust_Name);
            
            if((flag1 && flag2&& flag3)==false)
            {
               if(flag1==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid IP Adress</b></html>");
               else if(flag2==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Phone No</b></html>");
               else if(flag3==false)
                  JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Name</b></html>");
  
            }
            
            else
                

            {

                String operator=null;

                //System.out.print(jComboBox1.getSelectedItem().toString());
                if(jComboBox1.getSelectedIndex() != -1)
                {operator=jComboBox1.getSelectedItem().toString();
                    int operator_id=1;
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection(url,un,pass);

                    Statement st=con.createStatement();

                    Statement st2=con.createStatement();
                    Statement st3=con.createStatement();
                    Statement st4=con.createStatement();

                    ResultSet rs=st2.executeQuery("SELECT operator_id FROM universal.operator where operator_name='"+operator+"';");
                    rs.next();
                    ResultSet rs2=st3.executeQuery("SELECT EXISTS(SELECT * from customer WHERE cust_user_id='"+cust_ip+"');");
                    rs2.next();

                    existingEntry=Integer.parseInt(rs2.getString(1));

                    if(existingEntry==0)
                    {
                        operator_id=Integer.parseInt(rs.getString(1));
                        String query5="insert into customer(cust_id,cust_Name,cust_user_id,cust_operator_id,cust_contact_no,cust_broadband) values('"+cust_id+"','"+cust_Name+"','"+cust_ip+"','"+operator_id+"','"+cust_phno+"','ALLIANCE');";

                        int i=st.executeUpdate(query5);

                        JOptionPane.showMessageDialog(this,"<html><b style=\"color:green;font-size:20px;\">Record updated</b></html>");

                        view();
                        autoId ();
                        txtName.setText("");
                        txtIp1.setText("");
                        txtIp2.setText("");
                        txtIp3.setText("");
                        txtIp4.setText("");
                        txtPhno.setText("");

                        jComboBox1.setSelectedIndex(-1);

                    }   else
                    JOptionPane.showMessageDialog(this,"<html><b style=\"color:yellow;font-size:20px;\">IP Address Already Exists</b></html>");

                }  else
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Local Operator Not Selected</b></html>");

            }
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void AllianceCustAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllianceCustAddActionPerformed
        // TODO add your handling code here:
        insertAlliance();
      
    }//GEN-LAST:event_AllianceCustAddActionPerformed

    private void AllianceCustAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AllianceCustAddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllianceCustAddKeyPressed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtName1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            insertgtpl();
    }//GEN-LAST:event_txtName1KeyPressed

    private void txtIp6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIp6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            insertgtpl();
    }//GEN-LAST:event_txtIp6KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            insertgtpl();
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void txtPhno1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhno1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            insertgtpl();
    }//GEN-LAST:event_txtPhno1KeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            insertAlliance();
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtIp4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIp4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIp4KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            insertAlliance();
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void txtPhnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhnoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            insertAlliance();
    }//GEN-LAST:event_txtPhnoKeyPressed

    private void jTableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientMouseClicked
        // TODO add your handling code here:
        
        
        int row=jTableClient.getSelectedRow();
       
       
        String braodband=(jTableClient.getModel().getValueAt(row,4 ).toString());
        String name=jTableClient.getModel().getValueAt(row,0 ).toString();
            String ip=jTableClient.getModel().getValueAt(row,1 ).toString();
            String ph_no=jTableClient.getModel().getValueAt(row,2 ).toString();
            String id="";
            int operator_id=-1;
            try {
                Statement st1=con.createStatement();
                 
            String query1=" select cust_id,cust_operator_id from customer  "
                          + "where cust_user_id='"+ip+"' ";
            ResultSet rs1=st1.executeQuery(query1);
            rs1.next();
           // System.out.print(rs1.getString(2));
           id=rs1.getString(1);
            operator_id=Integer.parseInt(rs1.getString(2));
             } catch (SQLException ex) {
                Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
            global_name=name;
            global_phno=ph_no;
            global_operator=operator_id;
            
            
            
        if(braodband .equals("ALLIANCE"))
        {   
            String[] ip_address=ip.split("\\.");  
           
            jLabel10.setText(id);
             txtName.setText(name);
             txtIp1.setText(ip_address[0]);
             txtIp2.setText(ip_address[1]);
             txtIp3.setText(ip_address[2]);
             txtIp4.setText(ip_address[3]);
             txtPhno.setText(ph_no);
             jComboBox1.setSelectedIndex(operator_id-1);
             global_ip=txtIp1.getText()+"."+txtIp2.getText()+"."+txtIp3.getText()+"."+txtIp4.getText();
             
            
            
            
        
            
            
        
            
        }
        if(braodband .equals("GTPL")){
           
            
            jLabel11.setText(id);
             txtName1.setText(name);
             txtIp6.setText(ip);
             txtPhno1.setText(ph_no);
             jComboBox2.setSelectedIndex(operator_id-1);
        global_userid=txtIp6.getText();
        }
        
    }//GEN-LAST:event_jTableClientMouseClicked

    private void AllianceCustupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllianceCustupdateActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            int cust_id=Integer.parseInt(jLabel10.getText());
            String cust_Name=txtName.getText().toUpperCase();

            String cust_ip1=txtIp1.getText();
            String cust_ip2=txtIp2.getText();
            String cust_ip3=txtIp3.getText();

            String cust_ip4=txtIp4.getText();
            boolean existingEntry=false;
            String cust_ip=cust_ip1+"."+cust_ip2+"."+cust_ip3+"."+cust_ip4;
            String cust_phno=txtPhno.getText();
            //System.out.print(cust_ip);
            boolean flag1=isValidIPAddress(cust_ip);
            boolean flag2=isValidPhno(cust_phno);
            boolean flag3=isValidName(cust_Name);
            
            
            if((flag1 && flag2&& flag3)==false)
            {
               if(flag1==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid IP Adress</b></html>");
               else if(flag2==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Phone No</b></html>");
               else if(flag3==false)
                  JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Name</b></html>");
  
            }
            
            else 
                

            { 
            
                
            

                String operator=null;

                //System.out.print(jComboBox1.getSelectedItem().toString());
                if(jComboBox1.getSelectedIndex() != -1)
                {operator=jComboBox1.getSelectedItem().toString();
                    int operator_id=1;
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection(url,un,pass);

                    Statement st=con.createStatement();

                    Statement st2=con.createStatement();
                    Statement st3=con.createStatement();
                    Statement st4=con.createStatement();

                    ResultSet rs=st2.executeQuery("SELECT operator_id FROM universal.operator where operator_name='"+operator+"';");
                    rs.next();
                    

                    
                    {
                        operator_id=Integer.parseInt(rs.getString(1));
                        String query5="Update customer  set cust_name='"+cust_Name+"',cust_user_id='"+cust_ip+"' ,cust_operator_id='"+operator_id+"',cust_contact_no='"+cust_phno+"' where cust_id='"+cust_id+"';";
                         if(!(global_name.equals(cust_Name)&& global_phno.equals(cust_phno)&& global_ip.equals(cust_ip)&& global_operator==operator_id))
                         {int i=st.executeUpdate(query5);
                        JOptionPane.showMessageDialog(this,"<html><b style=\"color:green;font-size:20px;\">Record updated</b></html>");


                        view();
                        autoId ();
                        txtName.setText("");
                        txtIp1.setText("");
                        txtIp2.setText("");
                        txtIp3.setText("");
                        txtIp4.setText("");
                        txtPhno.setText("");

                        jComboBox1.setSelectedIndex(-1);
                         }
                         else
                         
JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">No Changes Made</b></html>");

                         

                    }   

                }  else
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Local Operator Not Selected</b></html>");

            }
            
            
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_AllianceCustupdateActionPerformed

    private void AllianceCustupdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AllianceCustupdateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllianceCustupdateKeyPressed

    private void gtplCustUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtplCustUpdateActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int cust_id=Integer.parseInt(jLabel11.getText());
            String cust_Name=txtName1.getText().toUpperCase();
//System.out.print(cust_Name);
            int existingEntry;
            String cust_ip=txtIp6.getText();
            String cust_phno=txtPhno1.getText();
            //System.out.print(cust_ip);
            boolean flag1=isValidUsername(cust_ip);
            boolean flag2=isValidPhno(cust_phno);
            boolean flag3=isValidName(cust_Name);
            
            if((flag1 && flag2&& flag3)==false)
            {
               if(flag1==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid UserName</b></html>");
               else if(flag2==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Phone No</b></html>");
               else if(flag3==false)
                   JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Name</b></html>");
  
            }
            else 
               

            {

                String operator=null;

                //System.out.print(jComboBox1.getSelectedItem().toString());
                if(jComboBox2.getSelectedIndex() != -1)
                {operator=jComboBox2.getSelectedItem().toString();
                    int operator_id=1;
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection(url,un,pass);

                    Statement st=con.createStatement();

                    Statement st2=con.createStatement();
                    Statement st3=con.createStatement();
                    

                    ResultSet rs=st2.executeQuery("SELECT operator_id FROM universal.operator where operator_name='"+operator+"';");
                    rs.next();
                   
                    {
                        operator_id=Integer.parseInt(rs.getString(1));
                        String query5="Update customer  set cust_name='"+cust_Name+"',cust_user_id='"+cust_ip+"' ,cust_operator_id='"+operator_id+"',cust_contact_no='"+cust_phno+"' where cust_id='"+cust_id+"';";
                     if(!(global_name.equals(cust_Name) && global_userid.equals(cust_ip) && global_phno.equals(cust_phno)&& global_operator==operator_id))        

                     {  int i=st.executeUpdate(query5);

                        JOptionPane.showMessageDialog(this,"<html><b style=\"color:green;font-size:20px;\">Record updated</b></html>");
                        view();
                        autoId ();
                        txtName1.setText("");

                        txtIp6.setText("");
                        txtPhno1.setText("");

                        jComboBox2.setSelectedIndex(-1);

                    } else
                     {JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">No Changes Made</b></html>");
}
                         }
                         
                     
                     
                         
                     

                }  else
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Local Operator Not Selected</b></html>");

            }
            
            
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gtplCustUpdateActionPerformed

    private void gtplCustUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gtplCustUpdateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtplCustUpdateKeyPressed

    private void clearAllianceFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllianceFormActionPerformed
        // TODO add your handling code here:
        
                         view();
                        autoId ();
                        txtName.setText("");
                        txtIp1.setText("");
                        txtIp2.setText("");
                        txtIp3.setText("");
                        txtIp4.setText("");
                        txtPhno.setText("");

                        jComboBox1.setSelectedIndex(-1);
    }//GEN-LAST:event_clearAllianceFormActionPerformed

    private void clearAllianceFormKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearAllianceFormKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearAllianceFormKeyPressed

    private void clearGtplFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearGtplFormActionPerformed
        // TODO add your handling code here:
                       view();
                        autoId ();
                        txtName1.setText("");

                        txtIp6.setText("");
                        txtPhno1.setText("");

                        jComboBox2.setSelectedIndex(-1);
        
    }//GEN-LAST:event_clearGtplFormActionPerformed

    private void clearGtplFormKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearGtplFormKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearGtplFormKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllianceCustAdd;
    private javax.swing.JButton AllianceCustupdate;
    private javax.swing.JButton clearAllianceForm;
    private javax.swing.JButton clearGtplForm;
    private javax.swing.JButton filter1;
    private javax.swing.JButton gtplCustAdd;
    private javax.swing.JButton gtplCustUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableClient;
    private javax.swing.JButton reset;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtCust;
    private javax.swing.JTextField txtIp1;
    private javax.swing.JTextField txtIp2;
    private javax.swing.JTextField txtIp3;
    private javax.swing.JTextField txtIp4;
    private javax.swing.JTextField txtIp6;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhno;
    private javax.swing.JTextField txtPhno1;
    // End of variables declaration//GEN-END:variables

   
}
