/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package operatorPackage;

/**
 *
 * @author prasu
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPhno1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtIp6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        clearGtplForm = new javax.swing.JButton();
        gtplCustAdd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtIp1 = new javax.swing.JTextField();
        txtIp2 = new javax.swing.JTextField();
        txtIp3 = new javax.swing.JTextField();
        txtIp4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel230 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPhno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        AllianceCustAdd = new javax.swing.JButton();
        clearAllianceForm = new javax.swing.JButton();
        AllianceCustupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 170, 102));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 170, 102));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Customer No");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("jLabel10");

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Customer Name");

        txtName1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });
        txtName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtName1KeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Customer Ph No");

        txtPhno1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPhno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhno1KeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("User ID");

        txtIp6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIp6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIp6KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Local Operator");

        jComboBox2.setMinimumSize(new java.awt.Dimension(5, 19));
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        clearGtplForm.setBackground(new java.awt.Color(204, 170, 102));
        clearGtplForm.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clearGtplForm.setForeground(new java.awt.Color(255, 255, 255));
        clearGtplForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/Clear customer.png"))); // NOI18N
        clearGtplForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearGtplFormActionPerformed(evt);
            }
        });
        clearGtplForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearGtplFormKeyPressed(evt);
            }
        });

        gtplCustAdd.setBackground(new java.awt.Color(51, 153, 0));
        gtplCustAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gtplCustAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/addCustomer.png"))); // NOI18N
        gtplCustAdd.setText("Add");
        gtplCustAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtplCustAddActionPerformed(evt);
            }
        });
        gtplCustAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gtplCustAddKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtPhno1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(gtplCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(clearGtplForm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtPhno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gtplCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearGtplForm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("GTPL", jPanel4);

        jPanel5.setBackground(new java.awt.Color(141, 181, 128));

        txtIp1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtIp2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtIp3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIp3ActionPerformed(evt);
            }
        });

        txtIp4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIp4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIp4KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Customer No");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("jLabel10");

        jLabel230.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel230.setForeground(new java.awt.Color(0, 0, 102));
        jLabel230.setText("Customer Name");

        txtName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Customer Ph No");

        txtPhno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPhno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhnoKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("IP Address");

        jLabel19.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Local Operator");

        jComboBox1.setMinimumSize(new java.awt.Dimension(5, 19));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        AllianceCustAdd.setBackground(new java.awt.Color(51, 153, 0));
        AllianceCustAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AllianceCustAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/addCustomer.png"))); // NOI18N
        AllianceCustAdd.setText("Add");
        AllianceCustAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllianceCustAddActionPerformed(evt);
            }
        });
        AllianceCustAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AllianceCustAddKeyPressed(evt);
            }
        });

        clearAllianceForm.setBackground(new java.awt.Color(141, 181, 128));
        clearAllianceForm.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clearAllianceForm.setForeground(new java.awt.Color(255, 255, 255));
        clearAllianceForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/Clear customer.png"))); // NOI18N
        clearAllianceForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllianceFormActionPerformed(evt);
            }
        });
        clearAllianceForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearAllianceFormKeyPressed(evt);
            }
        });

        AllianceCustupdate.setBackground(new java.awt.Color(51, 102, 255));
        AllianceCustupdate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AllianceCustupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operatorPackage/update Customer.png"))); // NOI18N
        AllianceCustupdate.setText("Update");
        AllianceCustupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllianceCustupdateActionPerformed(evt);
            }
        });
        AllianceCustupdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AllianceCustupdateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel230, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(txtIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIp4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel19)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(AllianceCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AllianceCustupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllianceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10)
                        .addComponent(jLabel18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel230)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AllianceCustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AllianceCustupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clearAllianceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("ALLIANCE", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtName1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        insertgtpl();
    }//GEN-LAST:event_txtName1KeyPressed

    private void txtPhno1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhno1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        insertgtpl();
    }//GEN-LAST:event_txtPhno1KeyPressed

    private void txtIp6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIp6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        insertgtpl();
    }//GEN-LAST:event_txtIp6KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        insertgtpl();
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void clearGtplFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearGtplFormActionPerformed
        // TODO add your handling code here:
        view();
        autoId ();
        txtName1.setText("");

        txtIp6.setText("");
        txtPhno1.setText("");

        jComboBox2.setSelectedIndex(-1);

    }//GEN-LAST:event_clearGtplFormActionPerformed

    private void clearGtplFormKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearGtplFormKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearGtplFormKeyPressed

    private void gtplCustAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtplCustAddActionPerformed
        // TODO add your handling code here:
        insertgtpl();

    }//GEN-LAST:event_gtplCustAddActionPerformed

    private void gtplCustAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gtplCustAddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtplCustAddKeyPressed

    private void txtIp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIp3ActionPerformed

    private void txtIp4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIp4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIp4KeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        insertAlliance();
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtPhnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhnoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        insertAlliance();
    }//GEN-LAST:event_txtPhnoKeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        insertAlliance();
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void AllianceCustAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllianceCustAddActionPerformed
        // TODO add your handling code here:
        insertAlliance();

    }//GEN-LAST:event_AllianceCustAddActionPerformed

    private void AllianceCustAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AllianceCustAddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllianceCustAddKeyPressed

    private void clearAllianceFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllianceFormActionPerformed
        // TODO add your handling code here:

        view();
        autoId ();
        txtName.setText("");
        txtIp1.setText("");
        txtIp2.setText("");
        txtIp3.setText("");
        txtIp4.setText("");
        txtPhno.setText("");

        jComboBox1.setSelectedIndex(-1);
    }//GEN-LAST:event_clearAllianceFormActionPerformed

    private void clearAllianceFormKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearAllianceFormKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearAllianceFormKeyPressed

    private void AllianceCustupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllianceCustupdateActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int cust_id=Integer.parseInt(jLabel10.getText());
            String cust_Name=txtName.getText().toUpperCase();

            String cust_ip1=txtIp1.getText();
            String cust_ip2=txtIp2.getText();
            String cust_ip3=txtIp3.getText();

            String cust_ip4=txtIp4.getText();
            boolean existingEntry=false;
            String cust_ip=cust_ip1+"."+cust_ip2+"."+cust_ip3+"."+cust_ip4;
            String cust_phno=txtPhno.getText();
            //System.out.print(cust_ip);
            boolean flag1=isValidIPAddress(cust_ip);
            boolean flag2=isValidPhno(cust_phno);
            boolean flag3=isValidName(cust_Name);

            if((flag1 && flag2&& flag3)==false)
            {
                if(flag1==false)
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid IP Adress</b></html>");
                else if(flag2==false)
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Phone No</b></html>");
                else if(flag3==false)
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Invalid Name</b></html>");

            }

            else

            {

                String operator=null;

                //System.out.print(jComboBox1.getSelectedItem().toString());
                if(jComboBox1.getSelectedIndex() != -1)
                {operator=jComboBox1.getSelectedItem().toString();
                    int operator_id=1;
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection(url,un,pass);

                    Statement st=con.createStatement();

                    Statement st2=con.createStatement();
                    Statement st3=con.createStatement();
                    Statement st4=con.createStatement();

                    ResultSet rs=st2.executeQuery("SELECT operator_id FROM universal.operator where operator_name='"+operator+"';");
                    rs.next();

                    {
                        operator_id=Integer.parseInt(rs.getString(1));
                        String query5="Update customer  set cust_name='"+cust_Name+"',cust_user_id='"+cust_ip+"' ,cust_operator_id='"+operator_id+"',cust_contact_no='"+cust_phno+"' where cust_id='"+cust_id+"';";
                        if((global_name.equals(cust_Name)&& global_phno.equals(cust_phno)&& global_ip.equals(cust_ip)&& global_operator==operator_id))
                        {int i=st.executeUpdate(query5);

                            view();
                            autoId ();
                            txtName.setText("");
                            txtIp1.setText("");
                            txtIp2.setText("");
                            txtIp3.setText("");
                            txtIp4.setText("");
                            txtPhno.setText("");

                            jComboBox1.setSelectedIndex(-1);
                        }
                        else

                        JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">No Changes Made</b></html>");

                    }

                }  else
                JOptionPane.showMessageDialog(this,"<html><b style=\"color:Red;font-size:20px;\">Local Operator Not Selected</b></html>");

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AllianceCustupdateActionPerformed

    private void AllianceCustupdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AllianceCustupdateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllianceCustupdateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllianceCustAdd;
    private javax.swing.JButton AllianceCustupdate;
    private javax.swing.JButton clearAllianceForm;
    private javax.swing.JButton clearGtplForm;
    private javax.swing.JButton gtplCustAdd;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtIp1;
    private javax.swing.JTextField txtIp2;
    private javax.swing.JTextField txtIp3;
    private javax.swing.JTextField txtIp4;
    private javax.swing.JTextField txtIp6;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhno;
    private javax.swing.JTextField txtPhno1;
    // End of variables declaration//GEN-END:variables
}
